characters = ['Any Death Eater',
'Any Founder',
'Any Gryffindor',
'Any Hogwarts Ghost',
'Any Hufflepuff',
'Any Ministry Employee',
'Any Muggle',
'Any Order Member',
'Any Professor',
'Any Quidditch Player',
'Any Ravenclaw',
'Any Slytherin',
'Albus Severus Potter',
'Hugo Weasley',
'James Sirius Potter',
'Lily Luna Potter',
'Rose Weasley',
'Scorpius Malfoy',
'Teddy Lupin',
'Victoire Weasley',
'Andromeda Tonks',
'Arthur Weasley',
'Barty Crouch Jr',
'Bellatrix Lestrange',
'Cornelius Fudge',
'Dolores Umbridge',
'Dorcas Meadowes',
'Fenrir Greyback',
'James Potter',
'Regulus Black',
'Kingsley Shacklebolt',
'Lily Evans Potter',
'Lucius Malfoy',
'Marlene McKinnon',
'Mary MacDonald',
'Molly Weasley',
'Narcissa Malfoy',
'Peter Pettigrew',
'Petunia Dursley',
'Rabastan Lestrange',
'Remus Lupin',
'Rita Skeeter',
'Rodolphus Lestrange',
'Rubeus Hagrid',
'Severus Snape',
'Sirius Black',
'Ted Tonks',
'Tom Riddle/Voldemort',
'Vernon Dursley',
'Walburga Black',
'Alicia Spinnet',
'Angelina Johnson',
'Bill Weasley',
'Cedric Diggory',
'Charlie Weasley',
'Cho Chang',
'Colin Creevey',
'Cormac McLaggen',
'Daphne Greengrass',
'Dean Thomas',
'Draco Malfoy',
'Dudley Dursley',
'Fleur Delacour',
'Fred Weasley',
'George Weasley',
'Ginny Weasley',
'Gregory Goyle',
'Hannah Abbott',
'Harry Potter',
'Hermione Granger',
'Katie Bell',
'Lavender Brown',
'Lee Jordan',
'Luna Lovegood',
'Marcus Flint',
'Marietta Edgecombe',
'Neville Longbottom',
'Nymphadora Tonks',
'Oliver Wood',
'Padma Patil',
'Pansy Parkinson',
'Percy Weasley',
'Romilda Vane',
'Ron Weasley',
'Seamus Finnegan',
'Susan Bones',
'Viktor Krum',
'Vincent Crabbe']